# Site settings
title: jgsogo (tbd)
# email: jgsogo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog personal para ir poniendo aquí lo que se me va pasando por la cabeza (en construcción).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jgsogo.es" # the base hostname & protocol for your site
twitter_username: jgsogo
github_username:  jgsogo

# Build settings
markdown: kramdown


# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : UA-60394831-1
  getclicky :
    site_id :
    
# Settings for comments
comments:
  disqus:
    shortname: jgsogoes